accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("financial/", views.Financial.as_view(), name="financial"),
    path("", views.Home.as_view(), name="home"),
    path("social/", views.Social.as_view(), name="social"),
    path("bulletin/", views.Bulletin.as_view(), name="bulletin"),
    path("history/", views.History.as_view(), name="history"),
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
]

eventcalendar/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardView


urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
]

social/urls.py
from django.urls import path

from . import views

app_name = "social"


urlpatterns = [
    path("social/", views.social.as_view(), name="social"),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta name="description" content="Event Dashboard" />
    <!-- Twitter meta-->
    {% comment %} <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:site" content="@sajib1066" />
    <meta property="twitter:creator" content="@sajib1066" /> {% endcomment %}
    <!-- Open Graph Meta-->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Vali Admin" />
    <meta property="og:title" content="Vali - Free Bootstrap 4 admin theme" />
    {% comment %} <meta property="og:url" content="https://sajib1066.github.io/" />
    <meta property="og:image" content="https://sajib1066.github.io/images/me.jpg" /> {% endcomment %}
    <meta property="og:description" content="Event Dashboard" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
    <link rel="stylesheet" href="../static/bootstrap.min.css">
    <link rel="stylesheet" href="../static/main.css">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <title>{% block title %}Immaculate Conception: Copperton{% endblock title  %}</title>
    {% block extracss %}
    {% endblock extracss %}
  </head>
  <body class="app sidebar-mini">
    <!-- Navbar-->
    <header class="app-header">
      {% comment %} <a class="app-header__logo" href="#">Event Calendar</a> {% endcomment %}
      <!-- Sidebar toggle button-->
      <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
      <!-- Navbar Right Menu-->
      <nav class="navbar navbar-expand-lg navbar-dark">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <li>
              <a class="app-menu__item active" id="home" href="/"><i class="app-menu__icon fa fa-home"></i><span class="app-menu__label">Home</span></a>
            </li>
            <li>
              <a class="app-menu__item active" href="{% url 'calendarapp:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Calendar</span></a>
            </li>
            <li class="treeview">
              <a class="app-menu__item active" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Events</span><i class="treeview-indicator fa fa-angle-right"></i></a>
              <ul class="treeview-menu">
                <li>
                  <a class="treeview-item" href="{% url 'dashboard' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span></a>
                </li>
                <li>
                  <a class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o"></i> Running</a>
                </li>
                <li>
                  <a class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o"></i> Upcoming</a>
                </li>
                <li>
                  <a class="treeview-item" href="{% url 'calendarapp:all_events' %}"><i class="icon fa fa-circle-o"></i> All</a>
                </li>
              </ul>
            </li>
            {% comment %} <li>
              <a class="app-menu__item" href="#"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Docs</span></a>
            </li> {% endcomment %}
            <li>
              <a class="app-menu__item active" id="bulletin" href="/bulletin"><i class="app-menu__icon fa fa-newspaper-o"></i><span class="app-menu__label">Bulletin</span></a>
            </li>
            <li>
              <a class="app-menu__item active" id="history" href="/history"><i class="app-menu__icon fa fa-envelope"></i><span class="app-menu__label">The Knight's Corner</span></a>
            </li>
            <!-- <li>
              <a class="app-menu__item active" id="financial" href="/financial"><i class="app-menu__icon fa fa-money"></i><span class="app-menu__label">Donations</span></a>
            </li>
            <li>
              <a class="app-menu__item active" id="social" href="/social"><i class="app-menu__icon fa fa-group"></i><span class="app-menu__label">Our Community</span></a>
            </li> -->
            {% comment %} <li>
              <a class="app-menu__item active" id="logout" href="/logout"><i class="app-menu__icon fa fa-logout"></i><span class="app-menu__label">Logout</span></a>
            </li>
            {% else %}
            <li>
              <a class="app-menu__item active" id="login" href="/login"><i class="app-menu__icon fa fa-login"></i><span class="app-menu__label">Login</span></a>
            </li>
            <li>
              <a class="app-menu__item active" id="signUp" href="/sign-up"><i class="app-menu__icon fa fa-sign-up"></i><span class="app-menu__label">Sign Up</span></a>
            </li> {% endcomment %}
            {% endif %}
          </ul>
        <div class="nav-item" id="nav-link"> 
          <h2 class="text-light" id="home" href="/">Immaculate Conception Parish: Copperton, UT</h2>
        </div>
        <ul class="app-nav">
          {% comment %} <li class="app-search">
              <input class="app-search__input" type="search" placeholder="Search" />
              <button class="app-search__button"><i class="fa fa-search"></i></button>
          </li>{% endcomment %}
          <!-- User Menu-->
          <li class="dropdown">
            <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-sign-out fa-lg"></i></a>
            <ul class="dropdown-menu settings-menu dropdown-menu-right">
              {% comment %} <li>
                <a class="dropdown-item" href="#"><i class="fa fa-cog fa-lg"></i> Settings</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="fa fa-user fa-lg"></i> Profile</a>
              </li> {% endcomment %}
              <li>
                <a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="fa fa-sign-out fa-lg"></i> Sign Out</a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </header>
    <main class="app-content">
      <div class="app-title">
        {% block breadcrumb %}
        {% endblock breadcrumb %}
      </div>
      {% block content %}
      {% endblock content %}
      <!-- Footer -->
      <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4">
          <!-- Section: Social media -->
          <section class="mb-4">

            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/ImmaculateConceptionCopperton" role="button">
              <i class="fa fa-facebook-f"></i>
            </a>
        
            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.google.com/" role="button">
              <i class="fa fa-google"></i>
            </a>
        
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://instagram.com/koc17140?igshid=YmMyMTA2M2Y=" role="button">
              <i class="fa fa-instagram"></i>
            </a>
            
          </section>
          <!-- End Section: Social media -->
        
          <!-- Section: Form -->
        
          <!-- Section: Text -->
          <section class="mb-4">
            <a> Immaculate Conception Church </a>
            <p> 8892 W State Highway Copperton, UT 84006 </p>
            <a> (801)-569-2706 </a>
            </p>
          </section>
          <!-- Section: Text -->
        
          <!-- Section: Links -->
          <section class="">
            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">Sunday Schedule:</h5>
                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white">Rosary: 9:00am</a>
                  </li>
                  <li>
                    <a class="text-white">Mass: 9:30am </a>  
                  </li>
                </ul>
              </div>
              <!--Grid column-->
        
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">Confession Schedule</h5>
        
                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white">Saturdays: 5:00pm</a>
                  </li>
                  <!-- <li>
                    <a href="#!" class="text-white">Link 2</a>
                  </li>
                  <li>
                    <a href="#!" class="text-white">Link 3</a>
                  </li>
                  <li>
                    <a href="#!" class="text-white">Link 4</a>
                  </li> -->
                </ul>
              </div>
              <!--Grid column-->
        
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">Church Offerings</h5>
        
                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white">CCD</a>
                  </li>
                  <li>
                    <a class="text-white">First Holy Communion</a>
                  </li>
                  <li>
                    <a class="text-white">Baptismals</a>
                  </li>
                  <li>
                    <a class="text-white">RCIA</a>
                  </li>
                </ul>
              </div>
              <!--Grid column-->
        
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase">Pastor</h5>
                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white">Father Lourduraj Gally Gregory</a>
                    <div> </div> 
                  </li> 
                </ul>
                <h5 class="text-uppercase">Deacon</h5>
                <ul class="list-unstyled mb-0">
                  <li>
                    <a class="text-white">Paul Graham</a>
                  </li>
                </ul>
                <!-- <li>
                  <a href="#!" class="text-white">Link 3</a>
                </li>
                <li>
                  <a href="#!" class="text-white">Link 4</a>
                </li> -->
                </ul>
              </div>
              <!--Grid column-->
            </div>
            <!--Grid row-->
          </section>
          <!-- Section: Links -->
        </div>
        <!-- Grid container -->
        
        <!-- Section: Form -->
            
        <section class="">
          <form action="">
            <!--Grid row-->
            <div class="row d-flex justify-content-center">
              <!-- Grid column -->
              <div class="col-centered-12">
                <p class="col-justify-content-center">
                  <strong>Bulletin Sign Up</strong>
                </p>
              </div>
              <!--Grid column-->
        
              <!--Grid column-->
              <div class="col-md-5 col-12">
                <!-- Email input -->
                <div class="form-outline form-white mb-4">
                  <input type="email" id="form5Example21" class="form-control" />
                  <label class="form-label" for="form5Example21">Enter Email Address</label>
                </div>
              </div>
              <!--Grid column-->
        
              <!--Grid column-->
              <div class="col-auto">
                <!-- Submit button -->
                <button type="submit" class="btn btn-outline-light mb-4">
                  Subscribe
                </button>
              </div>
              <!--Grid column-->
            </div>
            <!--Grid row-->
          </form>
        </section>
    
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: navyblue;">
          © 2020 Copyright:
          <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
    </main>
    <!-- Essential javascripts for application to work-->
    {% include 'base/js.html' %}
    {% block extrascripts %}
    {% endblock extrascripts %}
  </body>
</html>

templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>