accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

bulletin/urls.py
from django.urls import path

from . import views

app_name = "bulletin"


urlpatterns = [
    path("bulletin/", views.bulletin, name="bulletin"),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("financial/", views.Financial.as_view(), name="financial"),
    path("", views.Home.as_view(), name="home"),
    path("social/", views.Social.as_view(), name="social"),
    path("bulletin/", views.Bulletin.as_view(), name="bulletin"),
    path("history/", views.History.as_view(), name="history"),
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
]

financial/urls.py
from django.urls import path

from . import views

app_name = "financial"


urlpatterns = [
    path("financial/", views.financial.as_view(), name="financial"),
]

history/urls.py
from django.urls import path

from . import views

app_name = "history"


urlpatterns = [
    path("history/", views.history.as_view(), name="history"),
]

social/urls.py
from django.urls import path

from . import views

app_name = "social"


urlpatterns = [
    path("social/", views.social.as_view(), name="social"),
]

calendarapp/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse

from calendarapp.models import EventAbstract
from accounts.models import User


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        events = Event.objects.filter(user=user, is_active=True, is_deleted=False)
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user,
            is_active=True,
            is_deleted=False,
            end_time__gte=datetime.now().date(),
        ).order_by("start_time")
        return running_events


class Event(EventAbstract):
    """ Event model """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("calendarapp:event-detail", args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse("calendarapp:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

accounts/views/signup.py
from django.views.generic import View
from django.shortcuts import render, redirect

from accounts.forms import SignUpForm


class SignUpView(View):
    """ User registration view """

    template_name = "accounts/signup.html"
    form_class = SignUpForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect("accounts:signin")
        context = {"form": forms}
        return render(request, self.template_name, context)

bulletin/views.py
from django.shortcuts import render

# Create your views here.

def bulletin(request):
	return render(request, "main/bulletin.html", {})

financial/views.py
from django.shortcuts import render

# Create your views here.

def financial(request):
	return render(request, "main/financial.html", {})

history/views.py
from django.shortcuts import render

# Create your views here.

def history(request):
	return render(request, "main/history.html", {})

social/views.py
from django.shortcuts import render

# Create your views here.

def social(request):
	return render(request, "main/social.html", {})

templates/add_member.html
{% extends 'base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
        <link rel="stylesheet" href="../static/bootstrap.min.css">
        <link rel="stylesheet" href="../static/main.css">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

templates/bulletin.html
{% extends "base/base.html" %}
{% block title %}Bulletin{% endblock %}
{% block content %}
{% load static %}
<!-- Container for the image gallery -->
<div class="container">

  <!-- Full-width images with number text -->
  <div class="mySlides">
    <div class="numbertext">1 / 4</div>
    <img src=/static/images/17July2022pg1.jpg style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">2 / 4</div>
      <img src=/static/images/17July2022pg2.jpg style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">3 / 4</div>
    <img src=/static/images/17July2022pg3.jpg style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">4 / 4</div>
    <img src=/static/images/17July2022pg4.jpg style="width:100%">
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>

  <!-- Image text -->
  <div class="caption-container">
    <p id="caption"></p>
  </div>

  <!-- Thumbnail images -->
  <div class="row">
    <div class="column">
      <img class="demo cursor" src=/static/images/17July2022pg1.jpg style="width:100%" onclick="currentSlide(1)" alt="17July2022pg1">
    </div>
    <div class="column">
      <img class="demo cursor" src=/static/images/17July2022pg2.jpg style="width:100%" onclick="currentSlide(2)" alt="17July2022pg2">
    </div>
    <div class="column">
      <img class="demo cursor" src=/static/images/17July2022pg3.jpg style="width:100%" onclick="currentSlide(3)" alt="17July2022pg3">
    </div>
    <div class="column">
      <img class="demo cursor" src=/static/images/17July2022pg4.jpg style="width:100%" onclick="currentSlide(4)" alt="17July2022pg4">
    </div>
  </div>
</div>
{% endblock %}

templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Welcome, {{ request.user }}</span>
    <a class="btn btn-info right" href="{% url 'accounts:signout' %}"> Sign Out</a>
	<a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> + New Event </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

templates/event-details.html
{% extends 'base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
        </div>

        <div class="clearfix">
            <h3>Event Name: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/financial.html
<!-- {% extends "base/base.html" %}
{% block title %}Financial{% endblock %}
{% block content %}
    <h1 align="center">Reocurring Donations - (BL)</h1>
    <h1 align="center">One Time Donation - (BL)</h1>
    <h1 align="center">Donation Tracker??? - (BL)</h1>
{% endblock %} -->

<!-- 
-----I found what appears to be a good financial video but Youtube was acting up and would not play the video. -----

Accepting payments in Flask is straightforward using Stripe Checkout. All you need to do is redirect to Stripe's checkout page after creating a session, and Stripe will process the payment for you. In this video, I show you exactly how you can get started with payments in Flask using Stripe Checkout.
Need one-on-one help with your project? I can help through my coaching program. Learn more here: https://prettyprinted.com/coaching
Get the code here: https://prettyprinted.com/l/ccJ
Join my free course on the basics of Flask-SQLAlchemy: https://prettyprinted.com/flasksql

Documentation Referenced in Video:
https://stripe.com/docs/payments/chec...

https://stripe.com/docs/stripe-cli

Web Development Courses: https://prettyprinted.com

Subscribe: http://www.youtube.com/channel/UC-QDf...
Twitter: https://twitter.com/pretty_printed
Github: https://github.com/prettyprinted -->

templates/history.html
{% extends "base/base.html" %}
{% block title %}KoC: 17140{% endblock %}
{% block content %}

<div class="homecontainer">
  <div class="col-left" align="center">
    <h3 strong align="center"> IC Copperton Council 17140 </h3>
      <!-- Facebook -->
      <!-- <h1 align="center">Facebook Link to Page: https://www.facebook.com/KoC17140/?ref=pages_you_manage </h1> -->
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.facebook.com/KoC17140" role="button">
        <i class="fa fa-facebook-f"></i>
      </a>
    <br></br>
    <h3 strong> Who We Are </h3>
    <p>
      Our goal is to help men and their families within our community
      grow closer to Christ through our programs, resources, and
      opportunities to live and spread our Catholic faith.
    </p>
    <br></br>
    <h3 strong>KoC Articles</h3>
    <p>
      <li>
        <a href="https://issuu.com/columbia-magazine/docs/columbiaoct22en"> Columbia Magazine Digital Copy </a>
      </li>
      <!-- <li>
    <a href="https://www.goodcatholic.com/tips-for-catholics-dealing-with-anxiety/"> Tips for Catholics Dealing With Anxiety </a>
    </li> -->
    </p>
    <h3 strong> KoC Resources </h3>
    <p>
      <li>
        <a href="https://www.kofc.org/en//index.html"> KoC Website </a>
      </li>
      <li>
        <a href="https://utahknights.org/"> Utah Knights </a>
      </li>
      <!-- <li>
        <a href="https://www.kofc.org/en//index.html"> KoC Website </a>
      </li> -->
      <br></br>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.facebook.com/UtahKofC/" role="button">
        <i class="fa fa-facebook-f"></i>
      </a>
      <a class="btn btn-outline-dark btn-floating m-1" href="https://www.twitter.com/KofC" role="button">
        <i class="fa fa-twitter"></i>
      </a>
    </p>

  </div>
  <div class="form-right" align="center">
    <div>
      <script src="https://www.cognitoforms.com/f/seamless.js" data-key="I_i4gyNtHEmOR1ST4litug" data-form="1"></script>
    </div>
  </div>
</div>
{% endblock %}

templates/home.html
{% extends "base/base.html" %}
{% block title %}Immaculate Conception of Copperton{% endblock %}
{% block content %}

<div class="homecontainer">
  <div class="col-left" align="center">
   <h3 strong>Prayer of the Month</h3>
    <p>
      O MOTHER of blessedness and most august Sanctuary of the Holy Ghost, I praise and greet thee, 
      and with most devout intention of mind recall to thee that unspeakable joy which thou didst 
      feel when with calmest trustfulness thou didst commend to the Divine Will thy whole unreserved 
      self, and all that was to be done to thee and in thee, saying: Behold the handmaid of the Lord: 
      beseeching thee that thou wouldst show thyself my Mother, and evermore succour me with the 
      saving help of thy compassionate heart. 
      <p>Amen.</p>  
    </p>

    <h3 strong>Verse of the Month</h3>
    <p>
          1 That which was from the beginning,
        that which we have heard, that which we
        have seen with our eyes, that which we
        saw, and our hands touched, concerning
        the Word of life 2 (and the life was revealed,
        and we have seen, and testify, and declare
        to you the life, the eternal life, which was
        with the Father, and was revealed to us);
        3 that which we have seen and heard we
        declare to you, that you also may have
        fellowship with us. Yes, and our fellowship
        is with the Father and with his Son, Jesus
        Christ.* 4 And we write these things to you,
        that our joy may be fulfilled.
    </p>
    <p>  
          5 This is the message which we have
        heard from him and announce to you, that
        God is light, and in him is no darkness at
        all. 6 If we say that we have fellowship
        with him and walk in the darkness, we
        lie and don’t tell the truth. 7 But if we
        walk in the light as he is in the light, we
        have fellowship with one another, and the
        blood of Jesus Christ his Son, cleanses us
        from all sin. 8 If we say that we have no sin,
        we deceive ourselves, and the truth is not
        in us. 9 If we confess our sins, he is faithful
        and righteous to forgive us the sins and to
        cleanse us from all unrighteousness. 10 If
        we say that we haven’t sinned, we make
        him a liar, and his word is not in us.
    </p>
        <p> ~ 1 John 1:1 </p>
   
    <!-- (psuedo code bible verse)
   When @home.html

   If today (or new day)
   
    select verse from catholic bible
    
    printverse()

    (psuedo code Prayers)
    When @home.html
 
    If today (or new day)
    
     select new catholic prayer from pdf
     
     printprayer()
 


    https://www.catholic.org/bible/
     -->
  </div>
  <div class="col-center" align="center">
    <img title="iclogo" src=/static/images/iclogo.png alt="iclogo"/><br /><br /><br />
  </div>
  <div class="col-right" align="center">
       <h3 strong>Quote of the Month</h3>
    <p>
      “Without the burden of afflictions it is 
      impossible to reach the height of grace.  
      The gift of grace increases as the 
      struggle increases.”  
      
      <p>~ St. Rose of Lima</p>
      
      <!--  https://mycatholic.life/inspiring-quotes/  -->
      <!-- Each week pick quote from Inspiring quotes from Catholic Saints (OR) Quotes on Suffering
      
      if Lent (find dates) the pick from Quotes for Lent (OR) Quotes on Fasting
    
    -->
    </p>

    <h3 strong>Catholic Articles</h3>
    <p>
      <li>
      <a href="https://www.amadorcatholic.com/10-ways-to-grow-your-faith"> 10 Ways to Grow Your Faith </a>
      </li>
      <li>
      <a href="https://www.goodcatholic.com/tips-for-catholics-dealing-with-anxiety/"> Tips for Catholics Dealing With Anxiety </a>
      </li>
    </p>
    

    <h3 strong> Catholic Resources </h3>
    <p>
      <li>
      <a href="https://www.catholic.com/"> Catholic Answers </a>
      </li>
      <!-- <li>
      <a href="https://www.goodcatholic.com/tips-for-catholics-dealing-with-anxiety/"> Tips for Catholics Dealing With Anxiety </a>
      </li> -->
    </p>
    
    

  </div>
</div>

<!-- <h1 align="center">Functional Map</h1> -->

<!-- <div align="center">
  <a href=https://www.christianquotes.info/pfd/thumbs/ChristianQuotesinfo/2.php><br /><br /><br />
  <img title="post1 photo" src=https://www.christianquotes.info/pfd/thumbs/ChristianQuotesinfo/1.jpg alt="post1 photo" /><br /><br /><br />
  </a><br /><br /><br />
</div> -->
   

<!-- <h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.data }}
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form> -->

    <!-- <div align="right">
      <img title="post1 photo" src=/static/images/bkground_19.jpg alt="post1 photo"/><br /><br /><br />
    </div> -->
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content%}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/social.html
<!-- {% extends "base/base.html" %}
{% block title %}Social{% endblock %}
{% block content %}
    <h1 align="center">Sunday Social Sign Up - Our Community or the calendar (BL)</h1>
    <h1 align="center">Event Images - (BL)</h1>
    <h1 align="center">Parishioners - Names To Faces - (BL)</h1>
    <h1 align="center">Group Chat - (BL)</h1>
    <h1 align="center">New Parishioner Registration Forms - Digital</h1>
{% endblock %} -->